name: "Test Multiple Jobs"

on:
  workflow_dispatch:
  
jobs:
  startupjob:
    name: Start Up
    runs-on: ubuntu-latest
    steps:
      - name: Set everything up
        run: echo "Setting up"
      - name: Maybe break it all
        run: exit 0

  testsjob:
    name: Run Tests
    needs: startupjob
    runs-on: ubuntu-latest
    steps:
      - name: Run the test suite
        run: echo "Running the tests"
      - name: Maybe pretend a test has failed
        run: exit 0

  teardownjob:
    if: always()
    name: Tear Down
    runs-on: ubuntu-latest
    needs: testsjob
    steps:
      - name: Tear Down
        run: echo "Tear Down Everything"
      - name: Maybe break this job too
        run: exit 0
        
      - name: Set overall status Failure
        if: ${{ failure() || needs.job2.result != 'success' }}
        run: echo 'FAILURE'
      - name: Set overall status Success
        if: ${{ success() && needs.job2.result == 'success' }}
        run: echo 'SUCCESS'
        
      - name: Notify via Endid
        uses: endid-app/endid-github-action@v2.0
        with:
          token: ${{ secrets.ENDID_TOKEN }}
          status: ${{ job.success() && job.needs.testsjob.result == 'success' }}
        
  
