name: "Test Multiple Jobs"

on:
  workflow_dispatch:
  
 jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Break it all
        run: cmdnotexist
        
  job2:
    if: always()
    name: Job 2
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Set overall status
        run: echo ${{ needs.job1.result }}
        
  
