name: "Test Multiple Jobs"

on:
  workflow_dispatch:
  
jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Break it all
        run: cmdnotexist

  job2:
    name: Job 2
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Break it all2
        run: cmdnotexist2

  job3:
    if: always()
    name: Job 3
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Set overall status
        run: echo ${{ needs.job2.result }}
      - name: Set overall status
        run: echo ${{ needs.job2.needs.job1.result }}
        
  
